### ISSUE TITLE
Final configuration override _default configuration

### ISSUE THREAD

**Issue by steevanb** [steevanb/php-url-test#2]
With this configuration :
```yaml
_default:
    expectedResponse:
        header:
            headers:
                X-Foo: Bar

url_test:
    expectedResponse:
        header:
           size: 403
```
Headers are not tested, cause `url_test` has `expectedResponse.header` defined.

It should be merged between `_default` configuration, and `url_test` configuration.
